### ISSUE TITLE
Broken after upgrading Alexa Media Player to v4.12.10

### ISSUE THREAD

**Issue by bengarding** [TheAppleFreak/home-assistant-blueprints#2]
This blueprint (partially) broke for me after upgrading HACS to `2.0.0` and Alexa Media Player to `v4.12.10`. I no longer see any devices in the list. It still sends the notification to all devices if I leave the field blank, but I'm unable to select individual Echo devices.

![Screenshot 2024-08-21 at 10 14 16 AM](https://github.com/user-attachments/assets/2f69fdfa-69a3-47bf-8673-c742c38341be)

**Comment by TheAppleFreak** [comment]
Hmm, that's strange. Gonna do testing once I update my own install. I'd been meaning to swap out the device selector with the "target" selector instead (the one that lets you select areas, devices, and entities) so this is as good a time as any to take a closer look at it.

**Comment by TheAppleFreak** [comment]
Just updated to HACS 2.0.0 and AMP to 4.12.10. Device selection is working on my end, even after a complete system restart, so I'm wondering what's happening on yours...
![image](https://github.com/user-attachments/assets/867ca866-ac2b-46e3-bc39-9eaadfec934e)

I guess try reinstalling AMP? The device selector only shows devices from the `alexa_media` integration, so that seems like it'd be the first place to mess around with it.

**Comment by TheAppleFreak** [comment]
[Seems that AMP 4.12.10 had a regression with device lists.](https://github.com/alandtse/alexa_media_player/issues/2477) A new version, 4.2.11, just released today to fix that. Can you try installing that and see if that fixes it?

**Comment by bengarding** [comment]
Yep after upgrading to 4.2.11 the devices are back!

**Comment by TheAppleFreak** [comment]
Excellent! Gonna close this in that case :3
